"""
Artifact generation: the public works notice (PDF) and closure calendar (ICS).

PRD red flag #6 calls this the proof that agents *act* rather than merely
detect-and-display, so both artifacts are real files a municipal office could
put on a noticeboard, not placeholders.

Every artifact carries a synthetic-data disclaimer (PRD §11) — we must never
produce something that could be mistaken for a genuine government notice.
"""

from __future__ import annotations

from datetime import date, datetime, timedelta, timezone
from io import BytesIO
from typing import Optional

from icalendar import Alarm, Calendar, Event
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

DISCLAIMER = (
    "SYNTHETIC DEMONSTRATION DATA — This notice was generated by DIYA, a "
    "prototype multi-agent coordination system, from synthetic planning records. "
    "It does not represent an actual municipal decision, an actual road closure, "
    "or any real government record."
)


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "NoticeTitle", parent=base["Title"], fontSize=16, leading=20,
            spaceAfter=2 * mm, alignment=TA_CENTER,
        ),
        "authority": ParagraphStyle(
            "Authority", parent=base["Normal"], fontSize=10.5, leading=14,
            alignment=TA_CENTER, textColor=colors.HexColor("#333333"),
        ),
        "heading": ParagraphStyle(
            "SectionHeading", parent=base["Heading2"], fontSize=11, leading=14,
            spaceBefore=5 * mm, spaceAfter=2 * mm,
            textColor=colors.HexColor("#000000"),
        ),
        "body": ParagraphStyle(
            "Body", parent=base["Normal"], fontSize=10, leading=14,
            alignment=TA_JUSTIFY, spaceAfter=2 * mm,
        ),
        "small": ParagraphStyle(
            "Small", parent=base["Normal"], fontSize=8, leading=11,
            textColor=colors.HexColor("#555555"),
        ),
        "disclaimer": ParagraphStyle(
            "Disclaimer", parent=base["Normal"], fontSize=7.5, leading=10,
            textColor=colors.HexColor("#8a6d00"),
        ),
    }


def _fmt(value: str) -> str:
    """2026-09-15 -> 15 September 2026."""
    try:
        return date.fromisoformat(value).strftime("%d %B %Y")
    except (ValueError, TypeError):
        return value


def _rupees(amount: int) -> str:
    if amount >= 10_000_000:
        return f"Rs {amount / 10_000_000:.2f} Crore"
    if amount >= 100_000:
        return f"Rs {amount / 100_000:.2f} Lakh"
    return f"Rs {amount:,}"


def build_pdf(
    *,
    notice_id: str,
    title: str,
    description: str,
    affected_area: str,
    closure_start: str,
    closure_end: str,
    departments: list[str],
    phases: Optional[list[dict]] = None,
    city: str = "",
    savings: int = 0,
    authority: str = "Office of the Municipal Commissioner",
) -> bytes:
    """Render the public works notice as a PDF and return its bytes."""
    styles = _styles()
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=18 * mm, bottomMargin=18 * mm,
        title=title,
        author="DIYA Citizen Notice Agent",
        subject=f"Consolidated public works notice — {affected_area}",
    )

    story = []
    story.append(Paragraph(authority, styles["authority"]))
    story.append(Paragraph(
        f"{city.title()} Municipal Corporation — Infrastructure Coordination Cell",
        styles["small"],
    ))
    story.append(Spacer(1, 4 * mm))
    story.append(HRFlowable(width="100%", thickness=1.2, color=colors.black))
    story.append(Spacer(1, 3 * mm))

    story.append(Paragraph("PUBLIC NOTICE — CONSOLIDATED INFRASTRUCTURE WORKS", styles["title"]))
    story.append(Paragraph(title, styles["authority"]))
    story.append(Spacer(1, 4 * mm))

    meta = Table(
        [
            ["Notice No.", notice_id.upper(), "Issued", _fmt(date.today().isoformat())],
            ["Closure from", _fmt(closure_start), "Closure until", _fmt(closure_end)],
        ],
        colWidths=[28 * mm, 55 * mm, 28 * mm, 55 * mm],
    )
    meta.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f4f4f4")),
        ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#f4f4f4")),
    ]))
    story.append(meta)

    story.append(Paragraph("Affected Area", styles["heading"]))
    story.append(Paragraph(affected_area, styles["body"]))

    story.append(Paragraph("Notice to Residents and Road Users", styles["heading"]))
    story.append(Paragraph(description, styles["body"]))
    story.append(Paragraph(
        "The works listed below have been <b>consolidated into a single closure "
        "window</b> by the Infrastructure Coordination Cell. Previously these were "
        "scheduled as separate excavations of the same stretch by different "
        "departments. Residents should expect one continuous work period instead "
        "of repeated closures.",
        styles["body"],
    ))

    if phases:
        story.append(Paragraph("Sequence of Works", styles["heading"]))
        rows = [["#", "Department", "Work", "From", "Until"]]
        for phase in phases:
            rows.append([
                str(phase.get("order", "")),
                phase.get("deptName", ""),
                phase.get("workType", ""),
                _fmt(phase.get("start", "")),
                _fmt(phase.get("end", "")),
            ])
        table = Table(rows, colWidths=[10 * mm, 32 * mm, 55 * mm, 34 * mm, 34 * mm])
        table.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#000000")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#fafafa")]),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(table)
        story.append(Spacer(1, 2 * mm))
        story.append(Paragraph(
            "Works are sequenced deepest-utility-first so that the road surface is "
            "restored only once, at the end of the programme.",
            styles["small"],
        ))

    story.append(Paragraph("Departments Involved", styles["heading"]))
    story.append(Paragraph(", ".join(departments), styles["body"]))

    if savings:
        story.append(Paragraph("Public Benefit", styles["heading"]))
        story.append(Paragraph(
            f"Consolidating these works avoids repeated excavation and restoration "
            f"of the same stretch, with an estimated public exchequer saving of "
            f"<b>{_rupees(savings)}</b>, and reduces the number of separate road "
            f"closures affecting residents to one.",
            styles["body"],
        ))

    story.append(Paragraph("Grievances", styles["heading"]))
    story.append(Paragraph(
        "Objections or representations may be submitted to the Infrastructure "
        "Coordination Cell within 15 days of the date of this notice, quoting the "
        f"notice number {notice_id.upper()}.",
        styles["body"],
    ))

    story.append(Spacer(1, 6 * mm))
    story.append(HRFlowable(width="100%", thickness=0.6, color=colors.HexColor("#999999")))
    story.append(Spacer(1, 2 * mm))
    story.append(Paragraph(
        f"Generated by the DIYA Citizen Notice Agent on "
        f"{datetime.now(timezone.utc).strftime('%d %B %Y at %H:%M UTC')}.",
        styles["small"],
    ))
    story.append(Spacer(1, 1.5 * mm))
    story.append(Paragraph(DISCLAIMER, styles["disclaimer"]))

    doc.build(story)
    return buffer.getvalue()


def build_ics(
    *,
    notice_id: str,
    title: str,
    description: str,
    affected_area: str,
    closure_start: str,
    closure_end: str,
    departments: list[str],
    phases: Optional[list[dict]] = None,
) -> bytes:
    """
    Build the closure calendar.

    One all-day event spans the full consolidated closure, plus one event per
    phase so a resident can see which trade is on their street in which week.
    """
    cal = Calendar()
    cal.add("prodid", "-//DIYA//Infrastructure Conflict Resolution//EN")
    cal.add("version", "2.0")
    cal.add("calscale", "GREGORIAN")
    cal.add("method", "PUBLISH")
    cal.add("x-wr-calname", f"Road Closure — {affected_area}")

    start = date.fromisoformat(closure_start)
    end = date.fromisoformat(closure_end)

    main = Event()
    main.add("uid", f"{notice_id}@diya.local")
    main.add("summary", title)
    main.add(
        "description",
        f"{description}\n\nDepartments: {', '.join(departments)}\n\n{DISCLAIMER}",
    )
    main.add("location", affected_area)
    main.add("dtstart", start)
    # DTEND is exclusive for all-day events, so add a day to include the last one.
    main.add("dtend", end + timedelta(days=1))
    main.add("dtstamp", datetime.now(timezone.utc))
    main.add("status", "CONFIRMED")
    main.add("transp", "TRANSPARENT")

    alarm = Alarm()
    alarm.add("action", "DISPLAY")
    alarm.add("description", f"Road closure begins tomorrow: {affected_area}")
    alarm.add("trigger", timedelta(days=-1))
    main.add_component(alarm)

    cal.add_component(main)

    for phase in phases or []:
        try:
            phase_start = date.fromisoformat(phase["start"])
            phase_end = date.fromisoformat(phase["end"])
        except (KeyError, ValueError):
            continue

        event = Event()
        event.add("uid", f"{notice_id}-phase-{phase.get('order', 0)}@diya.local")
        event.add(
            "summary",
            f"Phase {phase.get('order', '')}: {phase.get('workType', 'Works')} "
            f"({phase.get('deptName', '')})",
        )
        event.add("description", phase.get("rationale", ""))
        event.add("location", affected_area)
        event.add("dtstart", phase_start)
        event.add("dtend", phase_end + timedelta(days=1))
        event.add("dtstamp", datetime.now(timezone.utc))
        event.add("status", "CONFIRMED")
        cal.add_component(event)

    return cal.to_ical()
