'use client';

import {
  FileText,
  Download,
  Calendar,
  Clock,
  Building2,
  ExternalLink,
  AlertCircle,
} from 'lucide-react';
import { notices, conflicts } from '@/lib/mock-data';
import { cn, formatDate, formatDateTime, getStatusColor, getStatusBg } from '@/lib/utils';

export default function NoticesPage() {
  return (
    <div className="page-container">
      <div className="flex items-start sm:items-center justify-between mb-5 sm:mb-6 flex-col sm:flex-row gap-2">
        <div>
          <h1 className="page-title">Citizen Notices</h1>
          <p className="page-subtitle">
            Public works notices generated by the Citizen Notice Agent for resolved conflicts
          </p>
        </div>
        <span className="text-xs text-diya-text-muted flex-shrink-0">{notices.length} notices generated</span>
      </div>

      {/* Info banner */}
      <div className="card mb-5 sm:mb-6 animate-fade-in">
        <div className="card-body flex items-start gap-3">
          <div className="w-8 h-8 rounded-lg bg-diya-info-dim flex items-center justify-center flex-shrink-0">
            <AlertCircle className="w-4 h-4 text-diya-info" />
          </div>
          <div className="min-w-0">
            <p className="text-sm font-medium mb-1">Real Artifact Generation</p>
            <p className="text-xs text-diya-text-secondary leading-relaxed">
              Each notice is a real, downloadable PDF and ICS calendar file generated by the Citizen Notice Agent.
              These are the &ldquo;real action&rdquo; proof point — the system produces tangible artifacts
              that a municipal office could actually distribute, not just dashboard visualizations.
            </p>
          </div>
        </div>
      </div>

      {/* Notices grid */}
      <div className="space-y-3 sm:space-y-4">
        {notices.map((notice) => (
          <div key={notice.id} className="card animate-fade-in">
            <div className="card-body">
              <div className="flex items-start justify-between mb-3 sm:mb-4 gap-2">
                <div className="flex items-start gap-3 min-w-0">
                  <div className="w-9 h-9 sm:w-10 sm:h-10 rounded-lg bg-diya-surface border border-diya-border flex items-center justify-center flex-shrink-0">
                    <FileText className="w-4 h-4 sm:w-5 sm:h-5 text-diya-text-secondary" strokeWidth={1.5} />
                  </div>
                  <div className="min-w-0">
                    <h3 className="text-xs sm:text-sm font-medium mb-1">{notice.title}</h3>
                    <p className="text-xs text-diya-text-secondary leading-relaxed line-clamp-3 sm:line-clamp-none">
                      {notice.description}
                    </p>
                  </div>
                </div>
                <span className={cn('badge flex-shrink-0', getStatusBg(notice.status), getStatusColor(notice.status))}>
                  {notice.status}
                </span>
              </div>

              {/* Details grid */}
              <div className="grid grid-cols-2 lg:grid-cols-4 gap-2 sm:gap-3 mb-3 sm:mb-4">
                <div className="bg-diya-surface rounded-md p-2.5 sm:p-3">
                  <div className="flex items-center gap-1.5 mb-1">
                    <Calendar className="w-3 h-3 text-diya-text-muted" />
                    <span className="text-[9px] sm:text-[10px] text-diya-text-muted uppercase tracking-wider">Closure</span>
                  </div>
                  <p className="text-[11px] sm:text-xs">
                    {formatDate(notice.closureWindow.start)} — {formatDate(notice.closureWindow.end)}
                  </p>
                </div>
                <div className="bg-diya-surface rounded-md p-2.5 sm:p-3">
                  <div className="flex items-center gap-1.5 mb-1">
                    <Building2 className="w-3 h-3 text-diya-text-muted" />
                    <span className="text-[9px] sm:text-[10px] text-diya-text-muted uppercase tracking-wider">Depts</span>
                  </div>
                  <p className="text-[11px] sm:text-xs truncate">{notice.departments.join(', ')}</p>
                </div>
                <div className="bg-diya-surface rounded-md p-2.5 sm:p-3">
                  <div className="flex items-center gap-1.5 mb-1">
                    <Clock className="w-3 h-3 text-diya-text-muted" />
                    <span className="text-[9px] sm:text-[10px] text-diya-text-muted uppercase tracking-wider">Generated</span>
                  </div>
                  <p className="text-[11px] sm:text-xs">{formatDateTime(notice.generatedAt)}</p>
                </div>
                <div className="bg-diya-surface rounded-md p-2.5 sm:p-3">
                  <div className="flex items-center gap-1.5 mb-1">
                    <AlertCircle className="w-3 h-3 text-diya-text-muted" />
                    <span className="text-[9px] sm:text-[10px] text-diya-text-muted uppercase tracking-wider">Ref</span>
                  </div>
                  <p className="text-[11px] sm:text-xs font-mono">{notice.conflictId}</p>
                </div>
              </div>

              {/* Affected area */}
              <div className="bg-diya-surface rounded-md p-2.5 sm:p-3 mb-3 sm:mb-4">
                <span className="text-[9px] sm:text-[10px] text-diya-text-muted uppercase tracking-wider block mb-1">
                  Affected Area
                </span>
                <p className="text-[11px] sm:text-xs text-diya-text-secondary">{notice.affectedArea}</p>
              </div>

              {/* Download actions */}
              <div className="flex items-center gap-2 sm:gap-3 pt-2 border-t border-diya-border flex-wrap">
                <button className="btn-primary flex items-center gap-2 text-xs">
                  <Download className="w-3.5 h-3.5" />
                  <span className="hidden sm:inline">Download</span> PDF
                </button>
                <button className="btn-secondary flex items-center gap-2 text-xs">
                  <Calendar className="w-3.5 h-3.5" />
                  <span className="hidden sm:inline">Download</span> ICS
                </button>
                <button className="btn-ghost flex items-center gap-2 text-xs ml-auto">
                  <ExternalLink className="w-3.5 h-3.5" />
                  <span className="hidden sm:inline">Public Link</span>
                </button>
              </div>
            </div>
          </div>
        ))}

        {/* Pending notices */}
        <div>
          <h2 className="text-sm font-medium text-diya-text-muted mb-3 mt-6 sm:mt-8">
            Pending — Awaiting Conflict Resolution
          </h2>
          {conflicts
            .filter((c) => c.status === 'detected')
            .map((conflict) => (
              <div key={conflict.id} className="card mb-3 opacity-60">
                <div className="card-body flex items-center gap-3">
                  <div className="w-8 h-8 rounded-lg bg-diya-surface border border-diya-border flex items-center justify-center flex-shrink-0">
                    <FileText className="w-4 h-4 text-diya-text-muted" strokeWidth={1.5} />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-xs font-medium text-diya-text-muted">
                      Notice pending for {conflict.id}
                    </p>
                    <p className="text-[10px] text-diya-text-muted truncate">
                      {conflict.works.length} works on {conflict.works[0]?.location.streetName} &middot;{' '}
                      Resolve conflict to generate notice
                    </p>
                  </div>
                  <span className="badge bg-diya-pending-dim text-diya-pending flex-shrink-0">awaiting</span>
                </div>
              </div>
            ))}
        </div>
      </div>
    </div>
  );
}
